import streamlit as st
import numpy as np
import trimesh
import tempfile
import plotly.graph_objects as go
from typing import List, Tuple, Optional
from datetime import date, datetime
from pathlib import Path

# =========================
# App basics
# =========================
st.set_page_config(page_title="3DCP Slicer", layout="wide")
st.title("3DCP Slicer")

EXTRUSION_K = 0.05
PATH_COLOR = "#222222"
OFFSET_COLOR = "rgba(255,0,0,0.35)"  # 연한 빨간색

def clamp(v, lo, hi):
    try:
        return lo if v < lo else hi if v > hi else v
    except Exception:
        return lo

# =========================
# Helpers
# =========================
def trim_segment_end(segment, trim_distance=30.0):
    segment = np.array(segment, dtype=float)
    if len(segment) < 2:
        return segment
    total_len = np.sum(np.linalg.norm(np.diff(segment, axis=0)[:, :2], axis=1))
    if total_len <= trim_distance:
        return segment
    trimmed = [segment[0]]
    acc = 0.0
    for i in range(1, len(segment)):
        p1, p2 = segment[i - 1], segment[i]
        d = np.linalg.norm((p2 - p1)[:2])
        if d == 0:
            continue
        if acc + d >= total_len - trim_distance:
            r = (total_len - trim_distance - acc) / d
            trimmed.append(p1 + (p2 - p1) * r)
            break
        trimmed.append(p2)
        acc += d
    return np.array(trimmed)

def simplify_segment(segment: np.ndarray, min_dist: float) -> np.ndarray:
    pts = np.asarray(segment, dtype=float)
    if len(pts) <= 2 or min_dist <= 0:
        return pts
    eps = float(min_dist) / 2.0

    def _perp_dist_xy(p, a, b) -> float:
        ab = b[:2] - a[:2]
        ap = p[:2] - a[:2]
        denom = np.dot(ab, ab)
        if denom <= 1e-18:
            return np.linalg.norm(ap)
        t = np.clip(np.dot(ap, ab) / denom, 0.0, 1.0)
        proj = a[:2] + t * ab
        return np.linalg.norm(p[:2] - proj)

    def _rdp_xy(points: np.ndarray, eps_val: float) -> np.ndarray:
        if len(points) <= 2:
            return points
        a, b = points[0], points[-1]
        dmax, idx = -1.0, -1
        for i in range(1, len(points) - 1):
            d = _perp_dist_xy(points[i], a, b)
            if d > dmax:
                dmax, idx = d, i
        if dmax <= eps_val:
            return np.vstack([a, b])
        left = _rdp_xy(points[: idx + 1], eps_val)
        right = _rdp_xy(points[idx:], eps_val)
        return np.vstack([left[:-1], right])

    return _rdp_xy(pts, eps)

def shift_to_nearest_start(segment, ref_point):
    idx = np.argmin(np.linalg.norm(segment[:, :2] - ref_point, axis=1))
    return np.concatenate([segment[idx:], segment[:idx]], axis=0), segment[idx]

# =========================
# G-code generator
# =========================
def generate_gcode(mesh, z_int=30.0, feed=2000, ref_pt_user=(0.0, 0.0),
                   e_on=False, start_e_on=False, start_e_val=0.1, e0_on=False,
                   trim_dist=30.0, min_spacing=3.0, auto_start=False, m30_on=False):
    g = ["; *** Generated by 3DCP Slicer ***", "G21", "G90"]
    if e_on:
        g.append("M83")

    z_max = mesh.bounds[1, 2]
    z_values = list(np.arange(z_int, z_max + 0.001, z_int))
    if abs(z_max - z_values[-1]) > 1e-3:
        z_values.append(z_max)
    z_values.append(z_max + 0.01)  # 최상단 캡쳐

    prev_start_xy = None
    for z in z_values:
        sec = mesh.section(plane_origin=[0, 0, z], plane_normal=[0, 0, 1])
        if sec is None:
            continue
        try:
            slice2D, to3D = sec.to_2D()
        except Exception:
            continue

        segments = []
        for seg in slice2D.discrete:
            seg = np.array(seg)
            seg3d = (to3D @ np.hstack([seg, np.zeros((len(seg), 1)), np.ones((len(seg), 1))]).T).T[:, :3]
            segments.append(seg3d)
        if not segments:
            continue

        g.append(f"\n; ---------- Z = {z:.2f} mm ----------")

        if auto_start and prev_start_xy is not None:
            dists = [np.linalg.norm(s[0][:2] - prev_start_xy) for s in segments]
            first_idx = int(np.argmin(dists))
            segments = segments[first_idx:] + segments[:first_idx]
            ref_pt_layer = prev_start_xy
        else:
            ref_pt_layer = np.array(ref_pt_user, dtype=float)

        for i_seg, seg3d in enumerate(segments):
            shifted, _ = shift_to_nearest_start(seg3d, ref_point=ref_pt_layer)
            trimmed = trim_segment_end(shifted, trim_dist)
            simplified = simplify_segment(trimmed, min_spacing)
            start = simplified[0]

            g.append(f"G01 F{feed}")
            if start_e_on:
                g.append(f"G01 X{start[0]:.3f} Y{start[1]:.3f} Z{z:.3f} E{start_e_val:.5f}")
            else:
                g.append(f"G01 X{start[0]:.3f} Y{start[1]:.3f} Z{z:.3f}")

            for p1, p2 in zip(simplified[:-1], simplified[1:]):
                dist = np.linalg.norm(p2[:2] - p1[:2])
                if e_on:
                    g.append(f"G01 X{p2[0]:.3f} Y{p2[1]:.3f} E{dist * EXTRUSION_K:.5f}")
                else:
                    g.append(f"G01 X{p2[0]:.3f} Y{p2[1]:.3f}")

            if e0_on:
                g.append("G01 E0")

            if i_seg == 0:
                prev_start_xy = start[:2]

    g.append(f"G01 F{feed}")
    if m30_on:
        g.append("M30")
    return "\n".join(g)

# =========================
# Slice path computation (미리보기용)
# =========================
def compute_slice_paths_with_travel(
    mesh,
    z_int=30.0,
    ref_pt_user=(0.0, 0.0),
    trim_dist=30.0,
    min_spacing=3.0,
    auto_start=False,
    e_on=False
) -> List[Tuple[np.ndarray, Optional[np.ndarray], bool]]:
    z_max = mesh.bounds[1, 2]
    z_values = list(np.arange(z_int, z_max + 0.001, z_int))
    if abs(z_max - z_values[-1]) > 1e-3:
        z_values.append(z_max)
    z_values.append(z_max + 0.01)

    all_items: List[Tuple[np.ndarray, Optional[np.ndarray], bool]] = []
    prev_layer_last_end: Optional[np.ndarray] = None
    prev_start_xy = None

    for z in z_values:
        sec = mesh.section(plane_origin=[0, 0, z], plane_normal=[0, 0, 1])
        if sec is None:
            continue
        try:
            slice2D, to3D = sec.to_2D()
        except Exception:
            continue

        segments = []
        for seg in slice2D.discrete:
            seg = np.array(seg)
            seg3d = (to3D @ np.hstack([seg, np.zeros((len(seg), 1)), np.ones((len(seg), 1))]).T).T[:, :3]
            segments.append(seg3d)
        if not segments:
            continue

        if auto_start and prev_start_xy is not None:
            dists = [np.linalg.norm(s[0][:2] - prev_start_xy) for s in segments]
            first_idx = int(np.argmin(dists))
            segments = segments[first_idx:] + segments[:first_idx]
            ref_pt_layer = prev_start_xy
        else:
            ref_pt_layer = np.array(ref_pt_user, dtype=float)

        layer_polys: List[np.ndarray] = []
        for i_seg, seg3d in enumerate(segments):
            shifted, _ = shift_to_nearest_start(seg3d, ref_point=ref_pt_layer)
            trimmed = trim_segment_end(shifted, trim_dist)
            simplified = simplify_segment(trimmed, min_spacing)
            layer_polys.append(simplified.copy())
            if i_seg == 0:
                prev_start_xy = simplified[0][:2]

        if not layer_polys:
            continue

        first_poly_start = layer_polys[0][0]
        if prev_layer_last_end is not None:
            travel = np.vstack([prev_layer_last_end, first_poly_start])
            all_items.append((travel, np.array([0.0, 0.0]) if e_on else None, True))

        for poly in layer_polys:
            if e_on:
                e_vals = [0.0]
                total = 0.0
                for p1, p2 in zip(poly[:-1], poly[1:]):
                    dist = np.linalg.norm(p2[:2] - p1[:2])
                    total += dist * EXTRUSION_K
                    e_vals.append(total)
                all_items.append((poly, np.array(e_vals), False))
            else:
                all_items.append((poly, None, False))

        prev_layer_last_end = layer_polys[-1][-1]

    return all_items

# === items -> segments (전체 사용) ===
def items_to_segments(items: List[Tuple[np.ndarray, Optional[np.ndarray], bool]],
                      e_on: bool
) -> List[Tuple[np.ndarray, np.ndarray, bool, bool]]:
    """
    반환: [(p1, p2, is_travel, is_extruding), ...]
    """
    segs: List[Tuple[np.ndarray, np.ndarray, bool, bool]] = []
    if not items:
        return segs
    for poly, e_vals, is_travel in items:
        if poly is None or len(poly) < 2:
            continue
        if e_on and e_vals is not None:
            for p1, p2, e1, e2 in zip(poly[:-1], poly[1:], e_vals[:-1], e_vals[1:]):
                is_extruding = (e2 - e1) > 1e-12 and (not is_travel)
                segs.append((p1, p2, is_travel, is_extruding))
        else:
            for p1, p2 in zip(poly[:-1], poly[1:]):
                segs.append((p1, p2, is_travel, True))  # E off면 전부 실선
    return segs

# === 누적 렌더 버퍼 (solid/dot + offset L/R) ===
def reset_anim_buffers():
    st.session_state.paths_anim_buf = {
        "solid": {"x": [], "y": [], "z": []},  # 압출
        "dot":   {"x": [], "y": [], "z": []},  # 트래블/비압출
        "off_l": {"x": [], "y": [], "z": []},  # 좌측(연빨)
        "off_r": {"x": [], "y": [], "z": []},  # 우측(연빨)
        "built_upto": 0,
    }

def ensure_anim_buffers():
    if "paths_anim_buf" not in st.session_state or not isinstance(st.session_state.paths_anim_buf, dict):
        reset_anim_buffers()

def append_segments_to_buffers(segments, start_idx, end_idx):
    buf = st.session_state.paths_anim_buf
    for i in range(start_idx, end_idx):
        p1, p2, is_travel, is_extruding = segments[i]
        key = "solid" if (not is_travel and is_extruding) else "dot"
        buf[key]["x"].extend([float(p1[0]), float(p2[0]), None])
        buf[key]["y"].extend([float(p1[1]), float(p2[1]), None])
        buf[key]["z"].extend([float(p1[2]), float(p2[2]), None])
    buf["built_upto"] = end_idx

def rebuild_buffers_to(segments, upto):
    reset_anim_buffers()
    if upto > 0:
        append_segments_to_buffers(segments, 0, upto)

def compute_offsets_into_buffers(segments, upto, half_width):
    """
    segments[0:upto] 중 '압출 세그먼트'만 대상으로
    진행 방향의 ±90°(좌/우)로 half_width 만큼 평행 이동한 선분을
    off_l, off_r 버퍼에 기록.
    """
    buf = st.session_state.paths_anim_buf
    # 초기화
    buf["off_l"] = {"x": [], "y": [], "z": []}
    buf["off_r"] = {"x": [], "y": [], "z": []}
    if half_width <= 0 or upto <= 0:
        return

    for i in range(0, min(upto, len(segments))):
        p1, p2, is_travel, is_extruding = segments[i]
        if is_travel or not is_extruding:
            continue
        dx = float(p2[0] - p1[0])
        dy = float(p2[1] - p1[1])
        nrm = (dx*dx + dy*dy) ** 0.5
        if nrm < 1e-12:
            continue
        # 좌측 법선(반시계 +90°) = (-dy, dx), 우측은 부호 반대
        nx = -dy / nrm
        ny =  dx / nrm

        l1 = (float(p1[0] + nx*half_width), float(p1[1] + ny*half_width), float(p1[2]))
        l2 = (float(p2[0] + nx*half_width), float(p2[1] + ny*half_width), float(p2[2]))
        r1 = (float(p1[0] - nx*half_width), float(p1[1] - ny*half_width), float(p1[2]))
        r2 = (float(p2[0] - nx*half_width), float(p2[1] - ny*half_width), float(p2[2]))

        # 좌
        buf["off_l"]["x"].extend([l1[0], l2[0], None])
        buf["off_l"]["y"].extend([l1[1], l2[1], None])
        buf["off_l"]["z"].extend([l1[2], l2[2], None])
        # 우
        buf["off_r"]["x"].extend([r1[0], r2[0], None])
        buf["off_r"]["y"].extend([r1[1], r2[1], None])
        buf["off_r"]["z"].extend([r1[2], r2[2], None])

def make_base_fig(height=820) -> go.Figure:
    fig = go.Figure()
    # 0: solid
    fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                               line=dict(width=3, dash="solid", color=PATH_COLOR),
                               showlegend=False))
    # 1: dot
    fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                               line=dict(width=3, dash="dot", color=PATH_COLOR),
                               showlegend=False))
    # 2: offset left (연빨)
    fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                               line=dict(width=2, dash="solid", color=OFFSET_COLOR),
                               name="Offset - Left", showlegend=False))
    # 3: offset right (연빨)
    fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                               line=dict(width=2, dash="solid", color=OFFSET_COLOR),
                               name="Offset - Right", showlegend=False))
    fig.update_layout(scene=dict(aspectmode="data"),
                      height=height, margin=dict(l=0, r=0, t=10, b=0),
                      uirevision="keep", transition={'duration': 0})
    return fig

def ensure_paths_fig(height=820):
    """세션의 paths_base_fig가 없거나 트레이스가 4개 미만이면 새로 만든다."""
    fig = st.session_state.get("paths_base_fig")
    ok = False
    try:
        ok = isinstance(fig, go.Figure) and (len(fig.data) >= 4)
    except Exception:
        ok = False
    if not ok:
        st.session_state.paths_base_fig = make_base_fig(height)

def ensure_four_traces(fig: go.Figure):
    """현재 fig의 트레이스 수를 확인해 4개가 되도록 부족한 만큼 추가."""
    def add_solid():
        fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                                   line=dict(width=3, dash="solid", color=PATH_COLOR),
                                   showlegend=False))
    def add_dot():
        fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                                   line=dict(width=3, dash="dot", color=PATH_COLOR),
                                   showlegend=False))
    def add_off():
        fig.add_trace(go.Scatter3d(x=[], y=[], z=[], mode="lines",
                                   line=dict(width=2, dash="solid", color=OFFSET_COLOR),
                                   showlegend=False))

    while len(fig.data) < 4:
        n = len(fig.data)
        if n == 0:
            add_solid()
        elif n == 1:
            add_dot()
        else:
            add_off()

def update_fig_with_buffers(fig: go.Figure, show_offsets: bool):
    # 항상 4트레이스 존재 보장
    ensure_four_traces(fig)

    buf = st.session_state.paths_anim_buf
    # main traces
    fig.data[0].x = buf["solid"]["x"]; fig.data[0].y = buf["solid"]["y"]; fig.data[0].z = buf["solid"]["z"]
    fig.data[1].x = buf["dot"]["x"];   fig.data[1].y = buf["dot"]["y"];   fig.data[1].z = buf["dot"]["z"]
    # offsets
    if show_offsets:
        fig.data[2].x = buf["off_l"]["x"]; fig.data[2].y = buf["off_l"]["y"]; fig.data[2].z = buf["off_l"]["z"]
        fig.data[3].x = buf["off_r"]["x"]; fig.data[3].y = buf["off_r"]["y"]; fig.data[3].z = buf["off_r"]["z"]
    else:
        fig.data[2].x = []; fig.data[2].y = []; fig.data[2].z = []
        fig.data[3].x = []; fig.data[3].y = []; fig.data[3].z = []

# =========================
# Plotly: STL (정적)
# =========================
def plot_trimesh(mesh: trimesh.Trimesh, height=820) -> go.Figure:
    v = mesh.vertices
    f = mesh.faces
    fig = go.Figure(data=[go.Mesh3d(
        x=v[:, 0], y=v[:, 1], z=v[:, 2],
        i=f[:, 0], j=f[:, 1], k=f[:, 2],
        color="#888888", opacity=0.6, flatshading=True
    )])
    fig.update_layout(scene=dict(aspectmode="data"),
                      height=height, margin=dict(l=0, r=0, t=10, b=0))
    return fig

# =========================
# Session init
# =========================
if "mesh" not in st.session_state:
    st.session_state.mesh = None
if "paths_items" not in st.session_state:
    st.session_state.paths_items = None
if "gcode_text" not in st.session_state:
    st.session_state.gcode_text = None
if "base_name" not in st.session_state:
    st.session_state.base_name = "output"

if "show_rapid_panel" not in st.session_state:
    st.session_state.show_rapid_panel = False
if "rapid_rx" not in st.session_state:
    st.session_state.rapid_rx = 0.0
if "rapid_ry" not in st.session_state:
    st.session_state.rapid_ry = 0.0
if "rapid_rz" not in st.session_state:
    st.session_state.rapid_rz = 0.0
if "rapid_text" not in st.session_state:
    st.session_state.rapid_text = None

# 진행(segments) 현재 위치 상태
if "paths_scrub" not in st.session_state:
    st.session_state.paths_scrub = 0  # 현재 표시 중인 세그먼트 개수

ensure_anim_buffers()

# =========================
# Sidebar
# =========================
st.sidebar.header("Access")
ALLOWED_WITH_EXPIRY = {"robotics5107": None, "kmou*": "2026-12-31"}
access_key = st.sidebar.text_input("Access Key", type="password", key="access_key")

def check_key_valid(k: str):
    if not k or k not in ALLOWED_WITH_EXPIRY:
        return False, None, None, "유효하지 않은 키입니다."
    exp = ALLOWED_WITH_EXPIRY[k]
    if exp is None:
        return True, None, None, "만료일 없음"
    try:
        exp_date = date.fromisoformat(exp)
    except Exception:
        return False, None, None, "키 만료일 형식 오류(YYYY-MM-DD)."
    today = date.today()
    remaining = (exp_date - today).days
    if remaining < 0:
        return False, exp_date, remaining, f"만료일 경과: {exp_date.isoformat()}"
    elif remaining == 0:
        return True, exp_date, remaining, f"오늘 만료 ({exp_date.isoformat()})"
    else:
        return True, exp_date, remaining, f"만료일: {exp_date.isoformat()} · {remaining}일 남음"

KEY_OK, EXP_DATE, REMAINING, STATUS_TXT = check_key_valid(access_key)
if access_key:
    if KEY_OK:
        if EXP_DATE is None:
            st.sidebar.success(STATUS_TXT)
        else:
            d_mark = f"D-{REMAINING}" if REMAINING > 0 else "D-DAY"
            st.sidebar.info(f"{STATUS_TXT} ({d_mark})")
    else:
        st.sidebar.error(STATUS_TXT)
else:
    st.sidebar.warning("Access Key를 입력하세요.")

uploaded = st.sidebar.file_uploader("Upload STL", type=["stl"], disabled=not KEY_OK)

st.sidebar.header("Parameters")
z_int = st.sidebar.number_input("Z interval (mm)", 1.0, 1000.0, 15.0)
feed = st.sidebar.number_input("Feedrate (F)", 1, 100000, 2000)
ref_x = st.sidebar.number_input("Reference X", value=0.0)
ref_y = st.sidebar.number_input("Reference Y", value=0.0)

st.sidebar.subheader("Extrusion options")
e_on = st.sidebar.checkbox("Insert E values")
start_e_on = st.sidebar.checkbox("Continuous Layer Printing", value=False, disabled=not e_on)
start_e_val = st.sidebar.number_input("Start E value", value=0.1, disabled=not (e_on and start_e_on))
e0_on = st.sidebar.checkbox("Add E0 at loop end", value=False, disabled=not e_on)

st.sidebar.subheader("Path processing")
trim_dist = st.sidebar.number_input("Trim/Layer Width (mm)", 0.0, 1000.0, 50.0)
min_spacing = st.sidebar.number_input("Minimum point spacing (mm)", 0.0, 1000.0, 3.0)
auto_start = st.sidebar.checkbox("Start next layer near previous start")
m30_on = st.sidebar.checkbox("Append M30 at end", value=False)

b1 = st.sidebar.container()
b2 = st.sidebar.container()
slice_clicked = b1.button("Slice Model", use_container_width=True)
gen_clicked = b2.button("Generate G-Code", use_container_width=True)

# =========================
# Load mesh on upload
# =========================
if uploaded is not None:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".stl") as tmp:
        tmp.write(uploaded.read())
        tmp_path = tmp.name
    mesh = trimesh.load_mesh(tmp_path)
    if not isinstance(mesh, trimesh.Trimesh):
        st.error("STL must contain a single mesh")
        st.stop()
    scale_matrix = np.eye(4)
    scale_matrix[2, 2] = 1.0000001
    mesh.apply_transform(scale_matrix)
    st.session_state.mesh = mesh
    st.session_state.base_name = Path(uploaded.name).stem or "output"

# =========================
# Actions
# =========================
if KEY_OK and slice_clicked and st.session_state.mesh is not None:
    items = compute_slice_paths_with_travel(
        st.session_state.mesh,
        z_int=z_int,
        ref_pt_user=(ref_x, ref_y),
        trim_dist=trim_dist,
        min_spacing=min_spacing,
        auto_start=auto_start,
        e_on=e_on
    )
    st.session_state.paths_items = items
    st.session_state.paths_scrub = 0
    reset_anim_buffers()
    st.success("Slicing complete")

if KEY_OK and gen_clicked and st.session_state.mesh is not None:
    gcode_text = generate_gcode(
        st.session_state.mesh, z_int=z_int, feed=feed, ref_pt_user=(ref_x, ref_y),
        e_on=e_on, start_e_on=start_e_on, start_e_val=start_e_val, e0_on=e0_on,
        trim_dist=trim_dist, min_spacing=min_spacing, auto_start=auto_start, m30_on=m30_on
    )
    st.session_state.gcode_text = gcode_text
    st.success("G-code ready")

if st.session_state.get("gcode_text"):
    base = st.session_state.get("base_name", "output")
    st.sidebar.download_button("G-code 저장", st.session_state.gcode_text,
                               file_name=f"{base}.gcode", mime="text/plain",
                               use_container_width=True)

# =========================
# Rapid(MODX)
# =========================
def _fmt_pos(v: float) -> str:
    s = f"{v:+.1f}"; sign = s[0]; intpart, dec = s[1:].split("."); intpart = intpart.zfill(4); return f"{sign}{intpart}.{dec}"
def _fmt_ang(v: float) -> str:
    s = f"{v:+.2f}"; sign = s[0]; intpart, dec = s[1: ].split("."); intpart = intpart.zfill(3); return f"{sign}{intpart}.{dec}"

PAD_LINE = '+0000.0,+0000.0,+0000.0,+000.00,+000.00,+000.00,+0000.0,+0000.0,+0000.0,+0000.0'
MAX_LINES = 64000

def _extract_xyz_lines_count(gcode_text: str) -> int:
    cnt = 0
    for raw in gcode_text.splitlines():
        t = raw.strip()
        if not (t.startswith(("G0","G00","G1","G01"))):
            continue
        has_xyz = any(p.startswith(("X","Y","Z")) for p in t.split())
        if has_xyz:
            cnt += 1
    return cnt

def gcode_to_cone1500_module(gcode_text: str, rx: float, ry: float, rz: float) -> str:
    lines_out = []
    cur_x = cur_y = cur_z = 0.0
    frx, fry, frz = _fmt_ang(rx), _fmt_ang(ry), _fmt_ang(rz)
    tail = "+0000.0,+0000.0,+0000.0,+0000.0"
    for raw in gcode_text.splitlines():
        t = raw.strip()
        # 🔧 여기 괄호 수정됨 (불필요한 닫는 괄호 제거)
        if not t or not t.startswith(("G0","G00","G1","G01")):
            continue
        parts = t.split(); has_xyz = False
        for p in parts:
            if p.startswith("X"):
                try: cur_x = float(p[1:]); has_xyz = True
                except: pass
            elif p.startswith("Y"):
                try: cur_y = float(p[1:]); has_xyz = True
                except: pass
            elif p.startswith("Z"):
                try: cur_z = float(p[1:]); has_xyz = True
                except: pass
        if not has_xyz:
            continue
        fx, fy, fz = _fmt_pos(cur_x), _fmt_pos(cur_y), _fmt_pos(cur_z)
        lines_out.append(f'{fx},{fy},{fz},{frx},{fry},{frz},{tail}')
        if len(lines_out) >= MAX_LINES:
            break
    while len(lines_out) < MAX_LINES:
        lines_out.append(PAD_LINE)
    ts = datetime.now().strftime("%Y-%m-%d %p %I:%M:%S")
    header = ("MODULE Converted\n"
              "!***************************************************************...****************************************************************\n"
              "!*\n"
              f"!*** Generated {ts} by Gcode→RAPID converter.\n"
              "!\n"
              "!*** data3dp syntax: X(mm), Y(mm), Z(mm), Rx(deg), Ry(deg), Rz(deg), A1,A2,A3,A4\n"
              "!\n"
              "!***************************************************************...****************************************************************\n")
    cnt_str = str(MAX_LINES)
    open_decl = f'VAR string sFileCount:="{cnt_str}";\nVAR string d3dpDynLoad{{{cnt_str}}}:=[\n'
    body = ""
    for i, ln in enumerate(lines_out):
        q = f'"{ln}"'
        body += (q + ",\n") if i < len(lines_out) - 1 else (q + "\n")
    close_decl = "];\nENDMODULE\n"
    return header + open_decl + body + close_decl

st.sidebar.markdown("---")
if KEY_OK:
    if st.sidebar.button("Generate Rapid", use_container_width=True):
        st.session_state.show_rapid_panel = True
    if st.session_state.show_rapid_panel:
        with st.sidebar.expander("Rapid Settings", expanded=True):
            st.session_state.rapid_rx = st.number_input("Rx (deg)", value=float(st.session_state.rapid_rx), step=0.1, format="%.2f")
            st.session_state.rapid_ry = st.number_input("Ry (deg)", value=float(st.session_state.rapid_ry), step=0.1, format="%.2f")
            st.session_state.rapid_rz = st.number_input("Rz (deg)", value=float(st.session_state.rapid_rz), step=0.1, format="%.2f")

            gtxt = st.session_state.get("gcode_text")
            over = None
            if gtxt is not None:
                xyz_count = _extract_xyz_lines_count(gtxt)
                over = (xyz_count > MAX_LINES)

            save_rapid_clicked = st.button("Save Rapid", use_container_width=True, disabled=(gtxt is None))
            if gtxt is None:
                st.info("먼저 Generate G-Code로 G-code를 생성하세요.")
            elif over:
                st.error("G-code가 64,000줄을 초과하여 Rapid 파일 변환할 수 없습니다.")
            elif save_rapid_clicked:
                st.session_state.rapid_text = gcode_to_cone1500_module(
                    gtxt, rx=st.session_state.rapid_rx, ry=st.session_state.rapid_ry, rz=st.session_state.rapid_rz
                )
                st.success("Rapid(MODX, cone1500 형식) 변환 완료")

            if st.session_state.get("rapid_text"):
                base = st.session_state.get("base_name", "output")
                st.download_button("Rapid 저장 (.modx)", st.session_state.rapid_text,
                                   file_name=f"{base}.modx", mime="text/plain",
                                   use_container_width=True)

# =========================
# Right: Viewers
# =========================
tab_stl, tab_paths, tab_gcode = st.tabs(["STL Preview", "Sliced Paths (3D)", "G-code Viewer"])

with tab_stl:
    if st.session_state.get("mesh") is not None:
        st.plotly_chart(plot_trimesh(st.session_state.mesh, height=820),
                        use_container_width=True, key="stl_chart",
                        config={"displayModeBar": False})
    else:
        st.info("STL을 업로드하세요.")

with tab_paths:
    if st.session_state.get("paths_items") is not None:
        # 세그먼트 준비
        segments = items_to_segments(st.session_state.paths_items, e_on=e_on)
        total_segments = len(segments)

        # 옵션: Layer width offsets 적용
        apply_offsets = st.checkbox(
            "Apply layer width offsets (± W/2)",
            value=False,
            help="Path processing의 Trim/Layer Width (mm)를 W로 사용하여, 진행 방향 기준 ±90°로 W/2 평행 오프셋 경로를 연한 빨간색으로 표시합니다."
        )

        # 진행(segments) 슬라이더 + 숫자 입력(우측) UI
        col1, col2 = st.columns([6, 2])
        default_val = int(clamp(st.session_state.paths_scrub, 0, total_segments))
        with col1:
            scrub = st.slider("진행(segments)", min_value=0, max_value=int(total_segments),
                              value=int(default_val), step=1,
                              help="해당 세그먼트까지 누적 표시")
        with col2:
            scrub_num = st.number_input("행 번호", min_value=0, max_value=int(total_segments),
                                        value=int(default_val), step=1,
                                        help="표시할 최종 세그먼트(행) 번호")

        # 동기화
        target = default_val
        if scrub != default_val:
            target = int(scrub)
        if scrub_num != default_val:
            target = int(scrub_num)
        target = int(clamp(target, 0, total_segments))

        # 버퍼 재구축/증분 반영
        built = st.session_state.paths_anim_buf["built_upto"]
        if target < built:
            rebuild_buffers_to(segments, target)
        elif target > built:
            append_segments_to_buffers(segments, built, target)
        st.session_state.paths_scrub = target  # 현재 위치 저장

        # 오프셋 버퍼 생성/지우기
        if apply_offsets:
            half_w = float(trim_dist) * 0.5  # Trim/Layer Width 의 절반
            compute_offsets_into_buffers(segments, target, half_w)
        else:
            st.session_state.paths_anim_buf["off_l"] = {"x": [], "y": [], "z": []}
            st.session_state.paths_anim_buf["off_r"] = {"x": [], "y": [], "z": []}

        # 차트 렌더 (오프셋 트레이스가 항상 존재하도록 보장)
        ensure_paths_fig(height=820)
        fig = st.session_state.paths_base_fig
        update_fig_with_buffers(fig, show_offsets=apply_offsets)

        placeholder = st.empty()
        placeholder.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

        st.caption(
            f"세그먼트 총 {total_segments:,} | 현재 {st.session_state.paths_scrub:,}"
            + (f" | Offsets: ON (W/2 = {float(trim_dist)*0.5:.2f} mm)" if apply_offsets else "")
        )

    else:
        st.info("슬라이싱을 실행하세요.")

with tab_gcode:
    if st.session_state.get("gcode_text"):
        st.code(st.session_state.gcode_text, language="gcode")
    else:
        st.info("G-code를 생성하세요.")

if not KEY_OK:
    st.warning("유효한 Access Key를 입력해야 프로그램이 작동합니다. (업로드/슬라이싱/G-code 버튼 비활성화)")
